=== liwei6797/sagacity-sqltoy/trunk/sqltoy-quickvo/src/main/resources/META-INF/schema/quickvo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.sagframe.com/schema/quickvo"
	xmlns:tns="http://www.sagframe.com/schema/quickvo"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.sagframe.com/schema/quickvo"
	elementFormDefault="qualified">
	<xsd:element name="quickvo">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element name="field-keywords" maxOccurs="1"
					minOccurs="0">
					<xsd:annotation>
						<xsd:documentation><![CDATA[字段命名关键词,用逗号分隔]]></xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:attribute name="value" type="xsd:string"
							use="required" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="property" maxOccurs="unbounded">
					<xsd:complexType mixed="true">
						<xsd:attribute name="file" type="xsd:string" />
						<xsd:attribute name="name" type="xsd:string" />
						<xsd:attribute name="value" type="xsd:string" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="datasource" minOccurs="1"
					maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:attribute name="name" type="xsd:string"
							default="0" />
						<xsd:attribute name="url" type="xsd:string"
							use="required" />
						<xsd:attribute name="driver" type="xsd:string"
							use="required" />
						<xsd:attribute name="username" type="xsd:string"
							use="required" />
						<xsd:attribute name="password" type="xsd:string"
							use="required" />
						<xsd:attribute name="catalog" type="xsd:string">
							<xsd:annotation>
								<xsd:documentation><![CDATA[DB2支持]]></xsd:documentation>
							</xsd:annotation>
						</xsd:attribute>
						<xsd:attribute name="schema" type="xsd:string">
							<xsd:annotation>
								<xsd:documentation><![CDATA[oracle,mysql,postgresql等支持]]></xsd:documentation>
							</xsd:annotation>
						</xsd:attribute>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="tasks" form="qualified" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence maxOccurs="unbounded">
							<xsd:element name="task" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence maxOccurs="unbounded">
										<xsd:element name="vo" minOccurs="0">
											<xsd:complexType>
												<xsd:attribute name="package"
													type="xsd:string" use="required" />
												<xsd:attribute name="substr" type="xsd:string"
													use="required" />
												<xsd:attribute name="name" type="xsd:string"
													use="required" />
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
									<xsd:attribute name="datasource"
										type="xsd:string" />
									<xsd:attribute name="active" type="xsd:boolean"
										use="required" />
									<xsd:attribute name="swagger-model"
										type="xsd:boolean" />
									<xsd:attribute name="author" type="xsd:string" />
									<xsd:attribute name="include" type="xsd:string"
										use="required" />
									<xsd:attribute name="exclude" type="xsd:string" />
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="dist" type="xsd:string" />
						<xsd:attribute name="encoding" type="xsd:string"
							default="UTF-8" />
					</xsd:complexType>
				</xsd:element>
				<!-- 主键生成机制配置 -->
				<xsd:element name="primary-key" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence minOccurs="0" maxOccurs="unbounded">
							<xsd:element name="table" minOccurs="0"
								maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:attribute name="name" type="xsd:string" />
									<xsd:attribute name="strategy" use="required">
										<xsd:simpleType>
											<xsd:restriction base="xsd:string">
												<xsd:enumeration value="generator" />
												<xsd:enumeration value="assign" />
												<xsd:enumeration value="sequence" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>
									<xsd:attribute name="generator">
										<xsd:simpleType>
											<xsd:restriction base="xsd:string">
												<xsd:enumeration value="default" />
												<xsd:enumeration value="UUID" />
												<xsd:enumeration value="snowflake" />
												<xsd:enumeration value="nanotime" />
												<xsd:enumeration value="redis" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>
									<xsd:attribute name="sequence" type="xsd:string" />
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<!-- 业务主键策略 -->
				<xsd:element name="business-primary-key" maxOccurs="1">
					<xsd:complexType>
						<xsd:choice maxOccurs="unbounded">
							<xsd:element name="table">
								<xsd:complexType>
									<xsd:attribute name="name" use="required"
										type="xsd:string" />
									<xsd:attribute name="column" use="required"
										type="xsd:string" />
									<xsd:attribute name="length" type="xsd:int" />
									<xsd:attribute name="sequence-size" type="xsd:int" />
									<xsd:attribute name="signature" type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
											<![CDATA[用来区分识别不同业务分配的字符标志]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="related-columns"
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
											<![CDATA[关联字段,用来组合业务主键的相关字段,可以是多个]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="generator" use="required"
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
											<![CDATA[example:redis、snowflake or like as @bean(beanName) ]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
								</xsd:complexType>
							</xsd:element>
						</xsd:choice>
					</xsd:complexType>
				</xsd:element>
				<!-- 主子表级联配置 -->
				<xsd:element name="cascade" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>
							<![CDATA[指定主表对应的子表操作模式,操作模式分:主表级联修改：一般分删除和停用(默认是删除)，load：级联加载,可以不写]]>
						</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence minOccurs="0" maxOccurs="unbounded">
							<xsd:element name="table" minOccurs="0"
								maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:attribute name="name" type="xsd:string" />
									<xsd:attribute name="update-cascade"
										type="xsd:string" />
									<xsd:attribute name="load" type="xsd:string"
										default="default" />
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<!-- ORM类型转换映射 -->
				<xsd:element name="type-mapping" maxOccurs="1">
					<xsd:annotation>
						<xsd:documentation>
							<![CDATA[数据类型对应关系，native-type表示特定数据库返回的字段类型; jdbc-type：表示对应jdbc标准的类型(见:java.sql.Types),jdbc-type主要用于vo  @Column注解中，设置 其类型，方便操作数据库插入或修改时设置类型;java-type:表示转换为java VO时类型]]>
						</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence maxOccurs="unbounded">
							<xsd:element name="sql-type" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:attribute name="native-types"
										type="xsd:string" use="required" />
									<xsd:attribute name="precision" type="xsd:string" />
									<xsd:attribute name="scale" type="xsd:string" />
									<xsd:attribute name="jdbc-type" type="xsd:string" />
									<xsd:attribute name="java-type" type="xsd:string"
										use="required" />
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== liwei6797/sagacity-sqltoy/trunk/sqltoy-showcase/tools/quickvo/quickvo.xml
<?xml version="1.0" encoding="UTF-8"?>
<quickvo xmlns="http://www.sagframe.com/schema/quickvo"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sagframe.com/schema/quickvo http://www.sagframe.com/schema/sqltoy/quickvo.xsd">
	<property file="../../src/main/resources/application.properties" />
	<property name="project.version" value="1.0.0" />
	<property name="project.name" value="sqltoy-showcase" />
	<property name="project.package" value="com.sagframe.sqltoy" />
	<property name="include.schema" value="false" />
	<!-- set method 是否支持返回对象自身(默认是true),即: public VO  setName(String name){this.name=name;return this;} -->
	<property name="field.support.linked.set" value="true" />
	<!-- oracle支持schema,mysql\DB2:catalog -->
	<datasource name="sqltoy" url="${jdbc.connection.url}"
		driver="${jdbc.connection.driver_class}" catalog="${jdbc.connection.catalog}"
		username="${jdbc.connection.username}"	password="${jdbc.connection.password}" />
	<tasks dist="../../src/main/java" encoding="UTF-8">
		<!-- 4.0.6之后增加datasource属性适应多数据库配置,swagger-model:对象是否支持swagger注解 -->
		<task active="true" author="zhongxuchen" include="^SQLTOY_\w+" datasource="sqltoy" swagger-model="false">
			<vo package="${project.package}.showcase.vo" substr="Sqltoy" name="#{subName}VO" />
		</task>
	</tasks>
	<!-- 主键策略配置:
	    identity类型的会自动产生主键策略，其他场景sqltoy根据主键类型和长度自动分配相应的策略方式. 
		strategy分:sequence\assign\generator 三种策略：
			sequence 需要指定数据库对应的sequence名称。
			assign   为手工赋值，
			generator为指定具体产生策略,目前分:default:22位长度的主键\nanotime:26位纳秒形式\snowflake雪花算法\uuid\redis
    -->
	<primary-key>
		<table name="SQLTOY_\w+|SYS_\w+" strategy="generator" generator="default" />
		<table name="SQLTOY_BIGINT_TABLE" strategy="generator" generator="snowflake"/>
		<!--<table name="xxxTABLE" strategy="sequence" sequence="SEQ_XXXX"/> -->
		<!--<table name="sys_staff_info" strategy="generator" generator="snowflake"/> -->
		<!--<table name="sys_staff_info" strategy="generator" generator="redis"/>  -->
	</primary-key>

	<!-- 基于redis产生有规则的业务主键 -->
	<business-primary-key>
		<!-- 1位购销标志_2位设备分类代码_6位日期_3位流水 (如果当天超过3位会自动扩展到4位) -->
		<!-- 业务主键可以充当实际的主键，如果字段是主键会覆盖原来的主键策略 -->
		<!-- 包含的三个宏:
		      @substr(${field},startIndex,length) 
		      @case(value,case1,value1,case2,value2,other)  
		      @df(yyMMdd) 日期格式化,如果不需要加入日期可以用@df('') 
		-->
		<table name="SQLTOY_DEVICE_ORDER_INFO" column="ORDER_ID" generator="redis"
			signature="${psType}@case(${deviceType},PC,PC,NET,NT,OFFICE,OF,SOFTWARE,SF,OT)@day(yyMMdd)"
			related-columns="psType,deviceType" length="12" />
	</business-primary-key>
	
	<!-- 主子表的级联关系 update-cascade:delete 表示对存量数据进行删除操作,也可以写成:ENABLED=0(sql片段,置状态为无效) -->
	<cascade>
		<table name="SQLTOY_DICT_DETAIL" update-cascade="delete" load="STATUS=1" />
	</cascade>

	<!-- 数据类型对应关系，native-types表示特定数据库返回的字段类型; jdbc-type：表示对应jdbc标准的类型(见:java.sql.Types), 
		主要用于vo @Column注解中，设置其类型,方便操作数据库插入或修改时设置类型;java-type:表示对应java对象的属性类型 -->
	<type-mapping>
		<!-- 保留1个范例,一般无需配置 -->
		<sql-type native-types="NUMBER,DECIMAL,NUMERIC"	precision="1..8" scale="0" jdbc-type="INTEGER" java-type="Integer" />
		<!-- 增加雪花算法的演示 -->
		<sql-type native-types="BIGINT"	jdbc-type="BIGINT" java-type="java.math.BigInteger" />
	</type-mapping>
</quickvo>
